{% set version = "0.8.0" %}
{% set build = 0 %}

# {{ PYTHON }} is not resolved properly in multi-output recipes...
{% set PYTHON = "python" %}
{% set PYTHON = "$PREFIX/bin/python" %}  # [linux]
{% set PYTHON = "%PREFIX%\\python" %}  # [win]

package:
  name: nvmath-split
  version: {{ version }}

source:
  - url: https://github.com/NVIDIA/nvmath-python/archive/refs/tags/v{{ ".".join(version.split(".")[:3]) }}.tar.gz
    sha256: 43171461f9e7902fd42d5754481b11c36e58a0b282f55b7f0b14b0a1de649094
    patches:
      - patches/0002-Update-example-for-Windows.patch  # [win]

build:
  number: {{ build }}
  skip: true  # [py < 310 or py > 313 or osx or ppc64le or not (cuda_compiler_version or "").startswith("13.1")]
  # debugging skips:
  # skip: true  # [py != 310]

# Have certain top-level requirements so conda-smithy can render the correct variants
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cuda') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python

outputs:

  - name: nvmath-python-core
    build:
      script:
        - export CUDA_PATH=$BUILD_PREFIX/targets/x86_64-linux/   # [linux64]
        - export CUDA_PATH=$BUILD_PREFIX/targets/sbsa-linux/     # [aarch64]
        - set CUDA_PATH=%BUILD_PREFIX%\Library                   # [win64]
        - >-
          {{ PYTHON }} -m pip install --no-deps --no-build-isolation -v .
      ignore_run_exports:
        - cuda-version
        - cuda-python
      ignore_run_exports_from:
        - cuda-cudart-dev
      force_ignore_keys:
        - pytorch
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}
        - {{ stdlib('c') }}
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - python                                 # [build_platform != target_platform]
        - cython >=3.2.0                         # [build_platform != target_platform]
        - cuda-profiler-api                      # [build_platform != target_platform]
      host:
        - cuda-bindings {{ cuda_compiler_version }}
        - cuda-profiler-api
        - cuda-version {{ cuda_compiler_version }}
        - cython >=3.2.0
        - pip
        - python
        - setuptools >=77.0.3
        - tomli >=2.0.1  # [py < 311]
      run:
        - cuda-version >=12,<14.0a0
        # pyproject.toml/dependencies
        - cuda-bindings
        - cuda-core >=0.3.2,<1.0
        - cuda-pathfinder >=1.3.2,<2.0
        - numpy >=1.25,<3
        - python
        - pywin32  # [win64]
      run_constrained:
        # pyproject.toml/project/dependency-groups/oldest
        - cupy >=12.1.0
        - pytorch >=2.1.0

  - name: nvmath-python
    build:
      force_ignore_keys:
        - pytorch
    requirements:
      run:
        - {{ pin_subpackage("nvmath-python-core", max_pin='x.x.x') }}
        # pyproject.toml/project/optional-dependencies/sysctkXX
        - cuda-bindings >=12.9.2,<14,!=13.0.0
        - cutensor >=2.3.1
        # pyproject.toml/project/optional-dependencies/cuXX
        - cuda-core
        - libcublas
        - cuda-nvrtc
        - cuda-cudart
        - libcudss 0.7.*
        - libcufft
        - libcurand
        - libcusolver
        - libcusparse
    test:
      source_files:
        - examples/fft
        - examples/linalg
        - examples/sparse
        - examples/tensor
        - tests/example_tests
      requires:
        - cupy
        - pip
        - pytest
        - pytorch  # [not win]
        - pytorch-gpu  # [not win and is_gpu_available]
        - scipy
      imports:
        - nvmath
        - nvmath.fft
        - nvmath.linalg
        - nvmath.sparse
        - nvmath.tensor
      commands:
        - pip check
        - pytest tests/example_tests/matmul_tests/ -k "example01 and not cpu" -v -ra  # [is_gpu_available]
        - pytest tests/example_tests/fft_tests/ -k "example01 and not (cpu or callback)" -v -ra  # [is_gpu_available]
        - pytest tests/example_tests/sparse_tests/ -k "example01" -v -ra  # [is_gpu_available]
        - pytest tests/example_tests/tensor_tests/ -k "example01" -v -ra  # [is_gpu_available]

  - name: nvmath-python-dx
    build:
      force_ignore_keys:
        - pytorch
    requirements:
      run:
        - {{ pin_subpackage("nvmath-python-core", max_pin='x.x.x') }}
        - {{ pin_subpackage("nvmath-python", max_pin='x.x.x') }}
        - nvmath-python
        # pyproject.toml/project/optional-dependencies/dx
        - numba
        - numba-cuda
        # pyproject.toml/project/optional-dependencies/cu12-dx
        - libmathdx >=0.3.1,<0.4.0
        - cuda-cccl >12.4.127
        - cuda-nvrtc !=12.4.*,!=12.5.0
        # Device APIs need headers for JIT compile
        - libcurand-dev
    test:
      requires:
        - pip
        - pytest  # [is_gpu_available]
        - cccl-python  # [is_gpu_available]
        - cffi  # [is_gpu_available]
        - cupy
        - scipy  # [win]
      source_files:
        - examples/device
        - examples/fft/*callback*.py
        - tests/example_tests
      imports:
        - nvmath.device  # [is_gpu_available]
        - nvmath
        - nvmath.fft
        - nvmath.linalg
        - nvmath.sparse
      commands:
        - pip check
        - pytest tests/example_tests/device_tests/ -v -ra -k "fp or curand"  # [is_gpu_available]
        - pytest tests/example_tests/fft_tests/ -k "callback" -v -ra  # [is_gpu_available]
    about:
      license: Apache-2.0
      license_file: LICENSE
      summary: Install this meta-package to use nvmath-python device features
      description: >-
        This is a meta-package which installs a some optional dependencies. The main package is nvmath-python.

  - name: nvmath-python-cpu
    build:
      force_ignore_keys:
        - pytorch
    requirements:
      run:
        - {{ pin_subpackage("nvmath-python-core", max_pin='x.x.x') }}
        - mkl >=2024  # [x86_64 or linux64]
        - libnvpl-fft0 >=0.3,<1  # [arm64 or aarch64]
        - libnvpl-blas0 >=0.3,<1  # [arm64 or aarch64]
    test:
      source_files:
        - examples/fft/example*cpu_execution.py
        - examples/linalg/generic/matmul/example*cpu*.py
        - tests/example_tests
      requires:
        - pip
        - pytest
        - pytorch  # [not win]
      imports:
        - nvmath
        - nvmath.fft
        - nvmath.linalg
      commands:
        - pip check
        - pytest tests/example_tests/fft_tests/ -k cpu -v -ra
        - pytest tests/example_tests/matmul_tests/ -k cpu -v -ra
    about:
      license: Apache-2.0
      license_file: LICENSE
      summary: Install this meta-package to use nvmath-python cpu features
      description: >-
        This is a meta-package which installs a some optional dependencies. The main package is nvmath-python.

  - name: nvmath-python-distributed
    build:
      skip: true  # [win]
      force_ignore_keys:
        - pytorch
    requirements:
      run:
        - {{ pin_subpackage("nvmath-python-core", max_pin='x.x.x') }}
        - {{ pin_subpackage("nvmath-python", max_pin='x.x.x') }}
        - mpi4py
        - nccl >=2.24.3
        - libcublasmp >=0.6.0
        - libcufftmp
        - libnvshmem3 >=3.2.5
    test:
      source_files:
        - examples/distributed
        - tests/example_tests
      requires:
        - pip
        - pytest
        - pytorch  # [not win]
        - pytorch-gpu  # [not win and is_gpu_available]
      imports:
        - nvmath
        - nvmath.distributed
        - nvmath.distributed.fft
      commands:
        - pip check
        # - mpiexec -n 2 pytest tests/example_tests/distributed_tests -v -ra -k "not sync"  # [is_gpu_available]
    about:
      license: Apache-2.0
      license_file: LICENSE
      summary: Install this meta-package to use nvmath-python distributed features
      description: >-
        This is a meta-package which installs a some optional dependencies. The main package is nvmath-python.

  - name: nvmath-python-install-test-12
    build:        # [not is_gpu_available]
      skip: true  # [not is_gpu_available]
    requirements:
      run:
        - cuda-version 12.*
        - nvmath-python
        - nvmath-python-cpu
        - nvmath-python-dx
        - nvmath-python-distributed  # [not win]
    test:
      imports:
        - nvmath
        - nvmath.distributed  # [not win]
        - nvmath.distributed.fft  # [not win]
        - nvmath.fft
        - nvmath.linalg
        - nvmath.sparse
        - nvmath.tensor

  - name: nvmath-python-install-test-13
    build:        # [not is_gpu_available]
      skip: true  # [not is_gpu_available]
    requirements:
      run:
        - cuda-version 13.*
        - nvmath-python
        - nvmath-python-cpu
        - nvmath-python-dx
        - nvmath-python-distributed  # [not win]
        - cupy
        # - pytorch-gpu
    test:
      imports:
        - nvmath
        - nvmath.distributed  # [not win]
        - nvmath.distributed.fft  # [not win]
        - nvmath.fft
        - nvmath.linalg
        - nvmath.sparse
        - nvmath.tensor
        - cupy
        - pytorch-gpu

about:
  home: https://developer.nvidia.com/nvmath-python
  license: Apache-2.0
  license_url: https://docs.nvidia.com/cuda/nvmath-python/latest/license.html
  license_file: LICENSE
  summary: NVIDIA Math Libraries for the Python Ecosystem
  description: >-
    nvmath-python aims to bring the power and performance of the NVIDIA math libraries to the Python ecosystem with intuitive, pythonic APIs. The ultimate goal is to provide users full access to all of the available library features in a variety of execution spaces.

    To enable optional features, install any of the following packages: nvmath-python-cpu, nvmath-python-dx.
  doc_url: https://docs.nvidia.com/cuda/nvmath-python
  dev_url: https://github.com/NVIDIA/nvmath-python

extra:
  feedstock-name: nvmath
  recipe-maintainers:
    - conda-forge/cuda
    - carterbox
    - leofang
